name: .NET

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore src/FileBrowserDesktop.csproj

      - name: Build
        run: dotnet build src/FileBrowserDesktop.csproj --configuration Release --no-restore

      - name: Publish
        run: sh ./package-release.sh
